version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: countries_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata_countries:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/countries_db
    ports:
      - "8000:8000"
volumes:
  pgdata_countries:
